## Changing the datatype of tensor

In [2]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [3]:
#create a new tensor with default datatype(float32)

B=tf.constant([1,7,1.3])

In [4]:
B.dtype

tf.float32

In [5]:
C=tf.constant([3,8])
C.dtype

tf.int32

In [6]:
# change dtype frpm float32 to float16(reduced precision)
B=tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 1.3], dtype=float16)>

In [7]:
#change dtype from int32 to float32

E=tf.cast(C,dtype=tf.float32)
E,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 8.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 8])>)

In [8]:
#change it to float16

E_float16=tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 8.], dtype=float16)>

### 'Aggregating Tensors'

`Aggregating tensors: Condesing them from multiple values down to a smaller amount of values`

In [9]:
#Get the absolute values
D=tf.constant([-8,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-8, -2])>

In [10]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 2])>

`Lets go through following forms of aggregation:`
* Get the maximum of a tensor
* Get the minimum of a tensor
* Get the Mean of a tensor
* Get the Sum of a tensor

In [11]:
import numpy as np
#Create a Random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([64, 74, 45, 72, 54, 52, 18,  6, 73,  2, 60, 64, 39, 34,  7, 22, 91,
        4,  7, 98, 53,  8, 16, 39, 64, 56, 82, 57, 19, 77, 61, 26, 42, 38,
       30, 68,  9, 65, 78, 91, 83, 76, 94, 15, 37, 94, 56, 64, 76, 88])>

In [12]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [13]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [15]:
#Find the Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [16]:
#Find the Sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2548>

In [17]:
#Find the variance
tf.reduce_variance(E)

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [18]:
tf.reduce_std(E)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'

In [19]:
import numpy as np
import tensorflow as tf

def reduce_var(x, axis=None, keepdims=False):
    """Variance of a tensor, alongside the specified axis.

    # Arguments
        x: A tensor or variable.
        axis: An integer, the axis to compute the variance.
        keepdims: A boolean, whether to keep the dimensions or not.
            If `keepdims` is `False`, the rank of the tensor is reduced
            by 1. If `keepdims` is `True`,
            the reduced dimension is retained with length 1.

    # Returns
        A tensor with the variance of elements of `x`.
    """
    m = tf.reduce_mean(x, axis=axis, keep_dims=True)
    devs_squared = tf.square(x - m)
    return tf.reduce_mean(devs_squared, axis=axis, keep_dims=keepdims)

def reduce_std(x, axis=None, keepdims=False):
    """Standard deviation of a tensor, alongside the specified axis.

    # Arguments
        x: A tensor or variable.
        axis: An integer, the axis to compute the standard deviation.
        keepdims: A boolean, whether to keep the dimensions or not.
            If `keepdims` is `False`, the rank of the tensor is reduced
            by 1. If `keepdims` is `True`,
            the reduced dimension is retained with length 1.

    # Returns
        A tensor with the standard deviation of elements of `x`.
    """
    return tf.sqrt(reduce_var(x, axis=axis, keepdims=keepdims))

In [20]:
reduce_std(E,axis=1, keepdims=True)

TypeError: Got an unexpected keyword argument 'keep_dims'

In [21]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=795>

In [22]:
pip list

Package                      Version
---------------------------- ---------
absl-py                      1.3.0
argon2-cffi                  20.1.0
asttokens                    2.0.5
astunparse                   1.6.3
attrs                        21.4.0
backcall                     0.2.0
beautifulsoup4               4.11.1
bleach                       4.1.0
cachetools                   5.2.0
certifi                      2022.6.15
cffi                         1.15.0
charset-normalizer           2.1.1
cloudpickle                  2.2.1
colorama                     0.4.4
debugpy                      1.5.1
decorator                    5.1.1
defusedxml                   0.7.1
dm-tree                      0.1.8
entrypoints                  0.4
executing                    0.8.3
fastjsonschema               2.15.1
flatbuffers                  22.10.26
gast                         0.4.0
google-auth                  2.14.1
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grp

In [23]:
!pip install -U tensorflow-probability==0.6.0

  Using cached tensorflow_probability-0.6.0-py2.py3-none-any.whl (790 kB)
  Attempting uninstall: tensorflow-probability
    Found existing installation: tensorflow-probability 0.17.0
    Uninstalling tensorflow-probability-0.17.0:
      Successfully uninstalled tensorflow-probability-0.17.0


In [24]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=795>

In [25]:
0.17.0

SyntaxError: invalid syntax (2081179701.py, line 1)

In [26]:
!pip install -U tensorflow-probability==0.17.0

  Using cached tensorflow_probability-0.17.0-py2.py3-none-any.whl (6.5 MB)
  Attempting uninstall: tensorflow-probability
    Found existing installation: tensorflow-probability 0.6.0
    Uninstalling tensorflow-probability-0.6.0:
      Successfully uninstalled tensorflow-probability-0.6.0


In [27]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=795>

In [28]:
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([64, 74, 45, 72, 54, 52, 18,  6, 73,  2, 60, 64, 39, 34,  7, 22, 91,
        4,  7, 98, 53,  8, 16, 39, 64, 56, 82, 57, 19, 77, 61, 26, 42, 38,
       30, 68,  9, 65, 78, 91, 83, 76, 94, 15, 37, 94, 56, 64, 76, 88])>

In [29]:
tf.math.reduce_std(E)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.

In [30]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.189331>

In [31]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=794.63837>

In [32]:
#To find the variance of the Tensor
#Use tf.math.reduce_variance(E)

### Find the positional maximum and minimum

In [33]:
#Create a new Tensor for finding the positional maximum and positional minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [34]:
#Find the Positional Maximum
tf.argmax(F)   #argmax will return the indices of max values along the axes 

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [35]:
np.argmax(F)

42

In [36]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [37]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [38]:
#check for equality
assert F[tf.argmax(F)]==tf.reduce_max(F)

In [39]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [40]:
#To find the positional minimum

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [41]:
np.argmin(F)

16

In [42]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [43]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [44]:
assert F[tf.argmin(F)]==tf.reduce_min(F)

In [45]:
F[tf.argmin(F)]==tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [46]:
assert F[tf.argmin(F)]==tf.reduce_max(F)

AssertionError: 

### Squeezing a Tensor (Removing all 1-dimensional axes)

In [47]:
#Create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [48]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [49]:
G_squeezed =tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [50]:
G_squeezed.shape

TensorShape([50])

### One hot Encoding Tensors

In [51]:
#Create a List of Tensors
some_list=[0,1,2,3] #for Example could be Red,blue,green,yellow

tf.one_hot(some_list)

TypeError: Missing required positional argument

In [52]:
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [53]:
#specify custom values for one hot Encoding

tf.one_hot(some_list,depth=4,on_value="benkii",off_value="birugali")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'benkii', b'birugali', b'birugali', b'birugali'],
       [b'birugali', b'benkii', b'birugali', b'birugali'],
       [b'birugali', b'birugali', b'benkii', b'birugali'],
       [b'birugali', b'birugali', b'birugali', b'benkii']], dtype=object)>

### Trying out more Tensor Math operations

#### squaring,log,square root

In [55]:
#create a New Tensor

H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [56]:
#squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [60]:
#Find the squareroot(will get error method requires non int type)
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [59]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [61]:
#Find the log
tf.log(H)

AttributeError: module 'tensorflow' has no attribute 'log'

In [62]:
tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log]

In [63]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>