# Indexing and Expanding Tensors

#### Indexing Tensors

Tensors can be indexed just like Lists.

In [ ]:
Get the first two elements of each dimension

In [2]:
import tensorflow as tf
rank4_tensor=tf.zeros(shape=[2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

#In python Lists

In [3]:
some_list=[2,3,4,5]
some_list[:2]

[2, 3]

In [4]:
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

#get the first element from each dimension from each index except for final one

In [6]:
some_list[:1]

[2]

In [7]:
rank4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [9]:
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

#get the first element from each dimension from each index

In [10]:
rank4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

#except second last one

In [11]:
rank4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [12]:
rank4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [14]:
rank4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

#### Expanding or Reshaping( changing or adding new dimension to tensor)

Create a rank tensor(2 dimension)

In [17]:
rank2_tensor=tf.constant([[10,7],
                         [3,4]])

In [18]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [20]:
rank2_tensor.shape,rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [23]:
#get the last element of each row of  our rank2 tensor 

In [24]:
some_list,some_list[-1]

([2, 3, 4, 5], 5)

In [28]:
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [29]:
#Adding an extra dimension to our rank2 tensor

In [40]:
rank3_tensor=rank2_tensor[:,:,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [41]:
rank3_tensor=rank2_tensor[...,tf.newaxis]

In [33]:
# in Python "..." means "all dimensions prior to"
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [39]:
print("dimension: ", rank3_tensor.ndim)
print("shape    : ", rank3_tensor.shape)

dimension:  3
shape    :  (2, 2, 1)


In [42]:
rank3_new_tensor=tf.expand_dims(rank2_tensor,axis=-1) #-1 means expand the final axis

In [43]:
rank3_new_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [38]:
print("dimension: ", rank3_new_tensor.ndim)
print("shape    : ", rank3_new_tensor.shape)

dimension:  3
shape    :  (2, 2, 1)


tf.newaxis is None in Numpy

In [46]:
#adding extra dimension at start/ 0-axis
tf.expand_dims(rank2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [47]:
#adding extra dimension in the middle
tf.expand_dims(rank2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

### manipulating Tensors (tensor operations) with basic operations

Basic operations
'+','-','*','/'

In [48]:
#adding values to tensor using addition operator

In [50]:
tensor_1=tf.constant([[10,7],
                     [3,4]])

In [51]:
tensor_1+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [52]:
#original tensor is unchanged
tensor_1


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [53]:
#multiplication
tensor_1*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [54]:
tensor_1


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [55]:
#subtraction
tensor_1-8

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, -1],
       [-5, -4]])>

In [56]:
tensor_1 #original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

we can also use tensorflow built-in fuctions also

In [59]:
tf.multiply(tensor_1,2)  #alias

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [60]:
tf.math.multiply(tensor_1,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

when we use tensorflow builtin fuction has a advantage of utilizing gpu capabalities when we do large operations

In [61]:
#still the original tensor is unchanged
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [62]:
tf.add(tensor_1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [66]:
tensor_1,tensor_1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

### Matrix multiplication with Tensors part-1

In machine Learning, matrix multiplication is one of the most common tensor operation

Matrix multiplication is the dotproduct of rows and columns

In [69]:
tf.matmul(tensor_1,tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

#This is an element wise multiplication

In [70]:
tensor_1*tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [72]:
tensor_2=tf.constant([[1,2,5],
                     [7,2,1],
                     [3,3,3]])
tensor_2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]])>

In [73]:
tensor_3=tf.constant([[3,5],
                     [6,7],
                     [1,8]])
tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]])>

In [77]:
#matrix multiplication is a dot product of rows and columns

[[(1*3+(2*6)+(5*1),(1*5)+(2*7)+(5*8))],
[(7*3)+(2*6)+(1*1),(7*5)+(2*7)+(1*8)],
[(3*3)+(3*6)+(3*1),(3*5)+(3*7)+(3*8)]]

[[(20, 59)], [34, 57], [30, 60]]

In [78]:
tf.matmul(tensor_2,tensor_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [80]:
#matrix multiplication with python operator @

tensor_2@tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [82]:
tensor_1@tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [84]:
tensor_1.shape

TensorShape([2, 2])

In [86]:
#Try to matrix multiplication of tensors of same shape
# creating same shape tensors of same shape(3,2)
x=tf.constant([[1,2],
              [3,4],
              [5,6]])

y=tf.constant([[7,8],
              [9,10],
              [11,12]])

In [87]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [89]:
x@y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [90]:
tf.matmul(x,y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

#   There are two rules our tensors(or matrices) need to fulfil if we are going to matrix multiply them:
 1)The inner dimensions must match
 2)The resulting matrix has the shape of the inner dimension